import type { DashboardSnapshot } from "../src/views/dashboard-model";

export const dashboardSnapshot: DashboardSnapshot = {
  definitions: [
    {
      description: "Find changes, update documentation, and check the result.",
      id: "docs",
      kind: "workflow",
      name: "update-documentation",
    },
    {
      description: "Review changed source files.",
      id: "review",
      kind: "workflow",
      name: "review-changes",
    },
    {
      description: "Summarize the day's completed work.",
      id: "summary",
      kind: "workflow",
      name: "summarize-day",
    },
    {
      description: "Check the configured API endpoint.",
      id: "api",
      kind: "step",
      name: "check-api",
    },
  ],
  harnesses: ["claude-code", "codex"],
  mode: "snapshot",
  root: "~/code/foundry/foundry",
  runs: [
    {
      definitionId: "docs",
      elapsed: "24s",
      id: "run-104",
      input: { options: { check: true }, paths: ["src/cli.ts"] },
      logs: [
        {
          id: "log-1",
          level: "info",
          message: "Run dispatched by update-docs.",
          timestamp: "14:31:44",
        },
        {
          id: "log-2",
          level: "info",
          message: "Found src/cli.ts",
          stepId: "find",
          timestamp: "14:31:46",
        },
        {
          id: "log-3",
          level: "debug",
          message: "Loaded cli.md",
          stepId: "read",
          timestamp: "14:31:50",
        },
        {
          id: "log-4",
          level: "info",
          message: "Writing CLI reference changes.",
          stepId: "write",
          timestamp: "14:32:08",
        },
      ],
      name: "update-documentation",
      started: "14:31:44",
      status: "running",
      steps: [
        {
          children: [],
          elapsed: "2s",
          id: "find",
          name: "Find changed files",
          result: "1 changed file",
          status: "complete",
        },
        {
          children: [
            {
              children: [],
              elapsed: "4s",
              id: "read",
              name: "Read existing docs",
              result: "Read cli.md",
              status: "complete",
            },
            {
              children: [],
              elapsed: "18s",
              id: "write",
              input: "Update the CLI reference.",
              name: "Write changes",
              status: "running",
            },
          ],
          elapsed: "22s",
          id: "update",
          name: "Update documentation",
          status: "running",
        },
      ],
      triggerId: "docs-monitor",
    },
    {
      definitionId: "api",
      elapsed: "3s",
      error: "Connection refused",
      id: "run-103",
      name: "check-api",
      started: "14:30:12",
      status: "failed",
      steps: [
        {
          children: [],
          error: "Connection refused",
          id: "request",
          name: "Request endpoint",
          status: "failed",
        },
      ],
    },
    {
      definitionId: "review",
      elapsed: "41s",
      id: "run-102",
      name: "review-changes",
      result: "Reviewed 3 files. No issues found.",
      started: "14:28:03",
      status: "complete",
      steps: [],
      triggerId: "review-monitor",
    },
  ],
  status: "Running · captured at 14:32:08",
  triggers: [
    {
      configuration: { debounce: "500ms", glob: "src/**/*.ts", kind: "files" },
      description: "Watch src/**/*.ts for documentation changes.",
      id: "docs-monitor",
      kind: "monitor",
      name: "update-docs",
      status: "running",
      targetId: "docs",
    },
    {
      description: "Watch src/**/* for code changes.",
      id: "review-monitor",
      kind: "monitor",
      name: "review-code",
      status: "watching",
      targetId: "review",
    },
    {
      configuration: {
        time: "17:00",
        weekdays: ["mon", "tue", "wed", "thu", "fri"],
      },
      description: "Every weekday at 17:00.",
      id: "daily",
      kind: "schedule",
      name: "daily-summary",
      next: "Today at 17:00",
      status: "waiting",
      targetId: "summary",
    },
  ],
  workspace: "foundry",
};
