import type { Adapter } from '../adapters/types';
import { ServiceRegistryImpl } from './registry';
import type { ServiceRegistry } from './registry';
import { CommandProcessorImpl } from './command-processor';
import type { CommandProcessor, CommandResult } from './command-processor';
import { WorkflowEngineImpl } from './workflow-engine';
import type {
  WorkflowEngine,
  WorkflowInstance,
  WorkflowContext,
} from './workflow-engine';
import { TaskManagerImpl } from './task-manager';
import type { TaskManager, TaskInput } from './task-manager';
import { DocumentGeneratorImpl } from '../generators/generator';
import type { DocumentGenerator } from '../generators/generator';
import type { Provider } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { createAnthropic } from '@ai-sdk/anthropic';
import { InMemoryAdapter } from '../adapters/in-memory';

export interface FoundryLibraryOptions {
  adapter?: Adapter;
  agents?: Record<string, Provider>;
}

export interface FoundryLibraryStatus {
  servicesReady: boolean;
  adapterReady: boolean;
  agentsReady: boolean;
  errors?: string[];
}

export interface FoundryLibraryInterface {
  executeCommand(
    command: string,
    args: Record<string, any>
  ): Promise<CommandResult>;
  startWorkflow(
    name: string,
    context: Record<string, any>
  ): Promise<WorkflowInstance>;
  getStatus(): Promise<FoundryLibraryStatus>;
}

export class FoundryLibrary implements FoundryLibraryInterface {
  private serviceRegistry: ServiceRegistry;
  private commandProcessor: CommandProcessor;
  private workflowEngine: WorkflowEngine;
  private taskManager: TaskManager;
  private documentGenerator: DocumentGenerator;

  constructor(options: FoundryLibraryOptions = {}) {
    const { OPENAI_API_KEY, ANTHROPIC_API_KEY } = process.env;

    const adapter = options.adapter || new InMemoryAdapter();
    const agents =
      options.agents ||
      ({
        default: null,
        research: null,
      } as Record<string, Provider | null>);

    if (!ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY is not set');
    } else {
      const claude = createAnthropic({
        apiKey: ANTHROPIC_API_KEY,
      }) as Provider;

      agents.default = claude;
    }

    if (OPENAI_API_KEY) {
      const openai = createOpenAI({
        apiKey: OPENAI_API_KEY,
      }) as Provider;

      agents.research = openai;
    } else {
      agents.research = agents.default;
    }

    // Initialize service registry
    this.serviceRegistry = new ServiceRegistryImpl();

    // Register provided components
    if (options.adapter) {
      this.serviceRegistry.registerAdapter('default', options.adapter);
    }

    if (options.agents) {
      Object.entries(options.agents).forEach(([name, provider]) => {
        const agent = provider;
        this.serviceRegistry.registerAgent(name, agent);
      });
    }

    // Initialize internal components
    this.commandProcessor = new CommandProcessorImpl(this.serviceRegistry);
    this.workflowEngine = new WorkflowEngineImpl(this.serviceRegistry);
    this.taskManager = new TaskManagerImpl(this.serviceRegistry);
    this.documentGenerator = new DocumentGeneratorImpl(this.serviceRegistry);

    // Register services in the registry
    this.serviceRegistry.registerService(
      'commandProcessor',
      this.commandProcessor
    );
    this.serviceRegistry.registerService('workflowEngine', this.workflowEngine);
    this.serviceRegistry.registerService('taskManager', this.taskManager);
    this.serviceRegistry.registerService(
      'documentGenerator',
      this.documentGenerator
    );

    // Register standard commands
    this.registerCommands();

    // Register standard workflows
    this.registerWorkflows();

    this.serviceRegistry.lock();
  }

  async executeCommand(
    command: string,
    args: Record<string, any>
  ): Promise<CommandResult> {
    return this.commandProcessor.execute(command, args);
  }

  async startWorkflow(
    name: string,
    context: Record<string, any>
  ): Promise<WorkflowInstance> {
    const workflowContext: WorkflowContext = {
      id: '', // Will be generated by the workflow engine
      data: context,
      results: {},
      currentStep: '', // Will be set by the workflow engine
      startedAt: new Date(),
      lastUpdatedAt: new Date(),
    };

    return this.workflowEngine.startWorkflow(name, workflowContext);
  }

  async getStatus(): Promise<FoundryLibraryStatus> {
    try {
      const healthStatus = await this.serviceRegistry.checkHealth();

      return {
        servicesReady: true,
        adapterReady: healthStatus.healthy,
        agentsReady: true, // Could implement more detailed agent health checks
        errors: healthStatus.issues
          ? Object.entries(healthStatus.issues).map(
              ([key, msg]) => `${key}: ${msg}`
            )
          : undefined,
      };
    } catch (error) {
      return {
        servicesReady: false,
        adapterReady: false,
        agentsReady: false,
        errors: [(error as Error).message],
      };
    }
  }

  private registerCommands(): void {
    // Register task management commands
    this.commandProcessor.registerCommand('tasks.list', async args => {
      return this.taskManager.getTasks(args);
    });

    this.commandProcessor.registerCommand('tasks.get', async args => {
      if (!args.id) throw new Error('Task ID is required');
      return this.taskManager.getTask(args.id);
    });

    this.commandProcessor.registerCommand('tasks.create', async args => {
      if (!args.title || !args.description)
        throw new Error('Title and description are required');
      const taskInput: TaskInput = {
        title: args.title,
        description: args.description,
        status: args.status,
        priority: args.priority,
        details: args.details,
        testStrategy: args.testStrategy,
        dependencies: args.dependencies,
      };
      return this.taskManager.createTask(taskInput);
    });

    this.commandProcessor.registerCommand('tasks.update', async args => {
      if (!args.id) throw new Error('Task ID is required');
      return this.taskManager.updateTask(args.id, args.updates || {});
    });

    this.commandProcessor.registerCommand('tasks.delete', async args => {
      if (!args.id) throw new Error('Task ID is required');
      return this.taskManager.deleteTask(args.id);
    });

    this.commandProcessor.registerCommand('tasks.status', async args => {
      if (!args.id || !args.status)
        throw new Error('Task ID and status are required');
      return this.taskManager.setTaskStatus(args.id, args.status);
    });

    // Register document generation commands
    this.commandProcessor.registerCommand(
      'documents.generatePRD',
      async args => {
        if (!args.concept) throw new Error('Concept is required');
        return this.documentGenerator.generatePRD(args.concept, args.options);
      }
    );

    this.commandProcessor.registerCommand(
      'documents.generateUserJourney',
      async args => {
        if (!args.persona || !args.scenario)
          throw new Error('Persona and scenario are required');
        return this.documentGenerator.generateUserJourney(
          args.persona,
          args.scenario
        );
      }
    );

    this.commandProcessor.registerCommand(
      'documents.generateTechSpec',
      async args => {
        if (!args.requirements) throw new Error('Requirements are required');
        return this.documentGenerator.generateTechnicalSpec(
          args.requirements,
          args.options
        );
      }
    );

    this.commandProcessor.registerCommand('documents.get', async args => {
      if (!args.id) throw new Error('Document ID is required');
      return this.documentGenerator.getDocument(args.id);
    });

    this.commandProcessor.registerCommand('documents.list', async args => {
      if (!args.type) throw new Error('Document type is required');
      return this.documentGenerator.listDocuments(args.type);
    });
  }

  private registerWorkflows(): void {
    // Register product creation workflow
    this.workflowEngine.registerWorkflow('product.create', {
      steps: [
        {
          name: 'concept',
          handler: async context => {
            // This step just validates that we have a concept
            if (!context.data.concept) {
              throw new Error('Concept is required');
            }

            // todo: capture prompt with greeting, if prompt is not provided
            return context.data.concept;
          },
        },
        {
          name: 'userJourney',
          handler: async context => {
            const persona = context.data.persona || 'Primary User';
            const scenario =
              context.data.scenario || `Using ${context.data.concept}`;

            return this.documentGenerator.generateUserJourney(
              persona,
              scenario
            );
          },
        },
        {
          name: 'prd',
          handler: async context => {
            const options = context.data.prdOptions || {};
            return this.documentGenerator.generatePRD(
              context.data.concept,
              options
            );
          },
        },
        {
          name: 'tasks',
          handler: async context => {
            // Implementation would parse the PRD and create tasks
            // This is a simplified version
            const prd = context.results.prd;

            // Just create a main task for now
            const mainTask = await this.taskManager.createTask({
              title: `Implement ${context.data.concept}`,
              description: `Implementation of ${context.data.concept} based on the PRD.`,
              details: `See PRD document ID: ${prd.id}`,
              priority: 'high',
            });

            return { mainTask };
          },
        },
      ],
      transitions: [
        { from: 'concept', to: 'userJourney', condition: 'always' },
        { from: 'userJourney', to: 'prd', condition: 'always' },
        { from: 'prd', to: 'tasks', condition: 'always' },
      ],
    });
  }
}
