import type { Provider } from "ai";

import { createAnthropic } from "@ai-sdk/anthropic";
import { createOpenAI } from "@ai-sdk/openai";

import type { Adapter } from "../adapters/types";
import type { Workflow } from "../agents/workflows";
import type { DocumentGenerator } from "../generators/generator";
import type { ServiceRegistry } from "./registry";
import type { TaskInput, TaskManager } from "./task-manager";

import { InMemoryAdapter } from "../adapters/in-memory";
import { DocumentGeneratorImpl } from "../generators/generator";
import { ServiceRegistryImpl } from "./registry";
import { TaskManagerImpl } from "./task-manager";
import { WorkflowEngineImpl } from "./workflow-engine";

export interface FoundryLibraryOptions {
  adapter?: Adapter;
  agents?: Record<string, Provider>;
}

export interface FoundryLibraryStatus {
  servicesReady: boolean;
  adapterReady: boolean;
  agentsReady: boolean;
  errors?: string[];
}

export interface FoundryLibraryInterface {
  execute(workflow: Workflow, args: Record<string, any>): Promise<any>;
  generate(type: string, args: Record<string, any>): Promise<string>;
  getStatus(): Promise<FoundryLibraryStatus>;
}

export class FoundryLibrary implements FoundryLibraryInterface {
  private serviceRegistry: ServiceRegistry;
  private workflowEngine: WorkflowEngine;
  private taskManager: TaskManager;
  private documentGenerator: DocumentGenerator;

  constructor(options: FoundryLibraryOptions = {}) {
    const { OPENAI_API_KEY, ANTHROPIC_API_KEY } = process.env;

    const adapter = options.adapter || new InMemoryAdapter();
    const agents =
      options.agents ||
      ({
        default: null,
        research: null,
      } as Record<string, Provider | null>);

    if (!ANTHROPIC_API_KEY) {
      throw new Error("ANTHROPIC_API_KEY is not set");
    } else {
      const claude = createAnthropic({
        apiKey: ANTHROPIC_API_KEY,
      }) as Provider;

      agents.default = claude;
    }

    if (OPENAI_API_KEY) {
      const openai = createOpenAI({
        apiKey: OPENAI_API_KEY,
      }) as Provider;

      agents.research = openai;
    } else {
      agents.research = agents.default;
    }

    // Initialize service registry
    this.serviceRegistry = new ServiceRegistryImpl();

    // Register provided components
    if (options.adapter) {
      this.serviceRegistry.registerAdapter("default", options.adapter);
    }

    if (options.agents) {
      Object.entries(options.agents).forEach(([name, provider]) => {
        const agent = provider;
        this.serviceRegistry.registerAgent(name, agent);
      });
    }

    // Initialize internal components
    this.workflowEngine = new WorkflowEngineImpl(this.serviceRegistry);
    this.taskManager = new TaskManagerImpl(this.serviceRegistry);
    this.documentGenerator = new DocumentGeneratorImpl(this.serviceRegistry);

    this.serviceRegistry.registerService("workflowEngine", this.workflowEngine);
    this.serviceRegistry.registerService("taskManager", this.taskManager);
    this.serviceRegistry.registerService(
      "documentGenerator",
      this.documentGenerator,
    );

    // Register standard commands
    this.registerCommands();

    // Register standard workflows
    this.registerWorkflows();

    this.serviceRegistry.lock();
  }

  async execute(command: string, args: Record<string, any>): Promise<any> {
    return this.agents.workflows.execute(command, args);
  }

  async generate(type: string, args: Record<string, any>): Promise<string> {
    const workflowContext: WorkflowContext = {
      id: "", // Will be generated by the workflow engine
      data: args,
      results: {},
      currentStep: "", // Will be set by the workflow engine
      startedAt: new Date(),
      lastUpdatedAt: new Date(),
    };

    return this.workflowEngine.startWorkflow(name, workflowContext);
  }

  async getStatus(): Promise<FoundryLibraryStatus> {
    try {
      const healthStatus = await this.serviceRegistry.checkHealth();

      return {
        servicesReady: true,
        adapterReady: healthStatus.healthy,
        agentsReady: true, // Could implement more detailed agent health checks
        errors: healthStatus.issues
          ? Object.entries(healthStatus.issues).map(
              ([key, msg]) => `${key}: ${msg}`,
            )
          : undefined,
      };
    } catch (error) {
      return {
        servicesReady: false,
        adapterReady: false,
        agentsReady: false,
        errors: [(error as Error).message],
      };
    }
  }

  private registerCommands(): void {}

  private registerWorkflows(): void {
    // Register product creation workflow
    this.workflowEngine.registerWorkflow("product.create", {
      steps: [
        {
          name: "concept",
          handler: async (context) => {
            // This step just validates that we have a concept
            if (!context.data.concept) {
              throw new Error("Concept is required");
            }

            // todo: capture prompt with greeting, if prompt is not provided
            return context.data.concept;
          },
        },
        {
          name: "userJourney",
          handler: async (context) => {
            const persona = context.data.persona || "Primary User";
            const scenario =
              context.data.scenario || `Using ${context.data.concept}`;

            return this.documentGenerator.generateUserJourney(
              persona,
              scenario,
            );
          },
        },
        {
          name: "prd",
          handler: async (context) => {
            const options = context.data.prdOptions || {};
            return this.documentGenerator.generatePRD(
              context.data.concept,
              options,
            );
          },
        },
        {
          name: "tasks",
          handler: async (context) => {
            // Implementation would parse the PRD and create tasks
            // This is a simplified version
            const prd = context.results.prd;

            // Just create a main task for now
            const mainTask = await this.taskManager.createTask({
              title: `Implement ${context.data.concept}`,
              description: `Implementation of ${context.data.concept} based on the PRD.`,
              details: `See PRD document ID: ${prd.id}`,
              priority: "high",
            });

            return { mainTask };
          },
        },
      ],
      transitions: [
        { from: "concept", to: "userJourney", condition: "always" },
        { from: "userJourney", to: "prd", condition: "always" },
        { from: "prd", to: "tasks", condition: "always" },
      ],
    });
  }
}
